// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXuC5BhrkIbTice8lCvu7OPxPu_O9Xi4w',
    appId: '1:989446467344:web:eb75ad43318d5a762dff95',
    messagingSenderId: '989446467344',
    projectId: 'snowprojectskj',
    authDomain: 'snowprojectskj.firebaseapp.com',
    storageBucket: 'snowprojectskj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRy-43xsSVZqHdwZE4QCwCtKkYarakjM',
    appId: '1:989446467344:android:535eaeb5150d23bf2dff95',
    messagingSenderId: '989446467344',
    projectId: 'snowprojectskj',
    storageBucket: 'snowprojectskj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIvIIXV9dilsQDAl7sWopgpnlaXKiuvw',
    appId: '1:989446467344:ios:d9c58868880099db2dff95',
    messagingSenderId: '989446467344',
    projectId: 'snowprojectskj',
    storageBucket: 'snowprojectskj.appspot.com',
    iosClientId: '989446467344-j19rck8p4lf28mallajktqovko8179s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaIvIIXV9dilsQDAl7sWopgpnlaXKiuvw',
    appId: '1:989446467344:ios:50877e184cb1f49c2dff95',
    messagingSenderId: '989446467344',
    projectId: 'snowprojectskj',
    storageBucket: 'snowprojectskj.appspot.com',
    iosClientId: '989446467344-gna8vr5u28tsrh5q16qtad1ai4sk7ovf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
